// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> spdfcoreVersion() =>
    RustLib.instance.api.crateFfiSpdfcoreVersion();

Future<int> getPageCount({required String filePath}) =>
    RustLib.instance.api.crateFfiGetPageCount(filePath: filePath);

Future<BigInt> getFileSize({required String filePath}) =>
    RustLib.instance.api.crateFfiGetFileSize(filePath: filePath);

Future<bool> validatePdf({required String filePath}) =>
    RustLib.instance.api.crateFfiValidatePdf(filePath: filePath);

Future<void> mergeFiles(
        {required List<String> inputFiles, required String outputFile}) =>
    RustLib.instance.api
        .crateFfiMergeFiles(inputFiles: inputFiles, outputFile: outputFile);

Future<void> splitByPages(
        {required String inputFile,
        required List<int> pages,
        required String outputFile}) =>
    RustLib.instance.api.crateFfiSplitByPages(
        inputFile: inputFile, pages: pages, outputFile: outputFile);

Future<void> extractPage(
        {required String inputFile,
        required int pageNumber,
        required String outputFile}) =>
    RustLib.instance.api.crateFfiExtractPage(
        inputFile: inputFile, pageNumber: pageNumber, outputFile: outputFile);

Future<void> splitAtPage(
        {required String inputFile,
        required int splitPage,
        required String outputPrefix}) =>
    RustLib.instance.api.crateFfiSplitAtPage(
        inputFile: inputFile, splitPage: splitPage, outputPrefix: outputPrefix);

Future<bool> isPdfPasswordProtected({required String filePath}) =>
    RustLib.instance.api.crateFfiIsPdfPasswordProtected(filePath: filePath);

Future<void> imageToPdf(
        {required String imagePath, required String outputPath}) =>
    RustLib.instance.api
        .crateFfiImageToPdf(imagePath: imagePath, outputPath: outputPath);

Future<void> imagesToPdf(
        {required List<String> imagePaths, required String outputPath}) =>
    RustLib.instance.api
        .crateFfiImagesToPdf(imagePaths: imagePaths, outputPath: outputPath);

Future<void> unlockPdf(
        {required String inputFile,
        required String password,
        required String outputFile}) =>
    RustLib.instance.api.crateFfiUnlockPdf(
        inputFile: inputFile, password: password, outputFile: outputFile);

Future<void> lockPdf(
        {required String inputFile,
        required String password,
        required String outputFile}) =>
    RustLib.instance.api.crateFfiLockPdf(
        inputFile: inputFile, password: password, outputFile: outputFile);
